### ISSUE TITLE
cooperation

### ISSUE THREAD

**Issue by yoavmil** [fililili/best_clipper#2]
Hi, my name is Yoav Miller. I am a computational algorithm developer. If you want to cooperate, maybe I can help.

**Comment by fililili** [comment]
Thanks for your reply, Yoav.
I found the algorithm randomly and don't have fully study about relating libraries and algorithms, so I am not sure whether the algorithm is valuable. I want to know whether anybody has discussed or implemented similar algorithm, if you know some clues, please let me know. And if nobody implements the algorithm before, we need more benchmark and unit test to see whether the algorithm works well. (even though I have written some tests, it's not enough)
For implementation, the algorithm for polygon Boolean operations is almost ready. But here are some things I still want to improve:
1. use boost::multiprecision or other big number lib to support precise geometry function.
2. try use GPU to speed up segments intersection queries, the step cost most of the time. I want study cuSpatial and use it.
Of course, if you have any other idea, just do it. Also, I am glad to answer any question about the algorithm.
